server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        # 인증 서비스 - 카카오 로그인 API
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/auth
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}
        # 인증 서비스 - Actuator API
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}
        # 인증 서비스 - refresh API, Logout API
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/auth/**
            - Method=POST,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}
            - AuthorizationHeaderFilter
        # 인증 서비스 - API 문서
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/docs/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}
        # 회원 서비스 - API 문서
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/docs/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        # 회원 서비스
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
            - AuthorizationHeaderFilter
        # 회원 서비스 - Actuator API
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        # 지역정보 서비스 - 지역정보 등록 - 어드민 권한 필요
        # 지역정보 서비스 - 검색 API
        - id: location-service
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/location-service/locations/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/location-service/(?<segment>.*),/$\{segment}
            - AuthorizationHeaderFilter
        # 지역정보 서비스 - API 문서
        - id: location-service
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/location-service/docs/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/location-service/(?<segment>.*),/$\{segment}
        # 스터디 서비스 - 카테고리 생성 API
        - id: study-service
          uri: lb://STUDY-SERVICE
          predicates:
            - Path=/study-service/categories
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/study-service/(?<segment>.*),/$\{segment}
            - AuthorizationHeaderFilter
        # 스터디 서비스 - 카테고리 수정/삭제 API
        - id: study-service
          uri: lb://STUDY-SERVICE
          predicates:
            - Path=/study-service/categories/**
            - Method=PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/study-service/(?<segment>.*),/$\{segment}
            - AuthorizationHeaderFilter
        # 스터디 서비스 - 카테고리 부모/자식 조회 API
        - id: study-service
          uri: lb://STUDY-SERVICE
          predicates:
            - Path=/study-service/categories/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/study-service/(?<segment>.*),/$\{segment}
        # 스터디 서비스 - 스터디 생성/수정/삭제/스터디 가입 신청 API
        - id: study-service
          uri: lb://STUDY-SERVICE
          predicates:
            - Path=/study-service/studies/**
            - Method=POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/study-service/(?<segment>.*),/$\{segment}
            - AuthorizationHeaderFilter
        # 스터디 서비스 - 스터디 검색/조회 API
        - id: study-service
          uri: lb://STUDY-SERVICE
          predicates:
            - Path=/study-service/studies/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/study-service/(?<segment>.*),/$\{segment}
        # 스터디 서비스 - API 문서
        - id: study-service
          uri: lb://STUDY-SERVICE
          predicates:
            - Path=/study-service/docs/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/study-service/(?<segment>.*),/$\{segment}



management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh
